unsigned int mikeos_bcd_to_int(unsigned char value);
int mikeos_check_for_key(void);
void mikeos_clear_screen(void);
int mikeos_create_file(char *filename);
unsigned int mikeos_dialog_box(char *message1, char *message2, char *message3, unsigned int buttons);
void mikeos_draw_background(char *message1, char *message2, unsigned int colour);
void mikeos_draw_block(unsigned char column, unsigned char row, unsigned char width, unsigned char height, unsigned char colour);
void mikeos_dump_registers(void);
void mikeos_dump_string(char *string);
void mikeos_fatal_error(char *message);
int mikeos_file_exists(char *filename);
int mikeos_file_selector(char *filename);
unsigned int mikeos_find_char_in_string(char *string, char character);
int mikeos_get_api_version(void);
void mikeos_get_cursor_pos(unsigned char *column, unsigned char *row);
void mikeos_get_date_string(char *buf);
void mikeos_get_file_list(char *buf);
int mikeos_get_file_size(char *filename);
unsigned int mikeos_get_random(unsigned int low, unsigned int high);
void mikeos_get_time_string(char *buf);
int mikeos_get_via_serial(unsigned char *data);
void mikeos_hide_cursor(void);
void mikeos_input_dialog(char *buf, char *message);
void mikeos_input_string(char *buf);
void mikeos_int_to_string(char *buf, unsigned int value);
int mikeos_list_dialog(char *list, char *message1, char *message2);
int mikeos_load_file(char *buf, char *filename);
long mikeos_long_int_negate(long value);
void mikeos_long_int_to_string(char *buf, unsigned long value, unsigned int base);
void mikeos_move_cursor(unsigned char column, unsigned char row);
void mikeos_pause(unsigned int deciseconds);
unsigned char mikeos_port_byte_in(unsigned short port);
void mikeos_port_byte_out(unsigned short port, unsigned char data);
void mikeos_print_1hex(unsigned char value);
void mikeos_print_2hex(unsigned char value);
void mikeos_print_4hex(unsigned int value);
void mikeos_print_digit(unsigned char value);
void mikeos_print_horiz_line(unsigned int style);
void mikeos_print_newline(void);
void mikeos_print_space(void);
void mikeos_print_string(char *message);
int mikeos_remove_file(char *filename);
int mikeos_rename_file(char *filename_new, char *filename_old);
int mikeos_run_basic(char *buf, int size);
int mikeos_send_via_serial(unsigned char data);
void mikeos_serial_port_enable(int mode);
void mikeos_set_date_fmt(unsigned int format);
void mikeos_set_time_fmt(unsigned char format);
void mikeos_show_cursor(void);
void mikeos_sint_to_string(char *buf, int value);
void mikeos_speaker_off(void);
void mikeos_speaker_tone(unsigned int divisor);
void mikeos_string_charchange(char *string, unsigned char newcharacter, unsigned char oldcharacter);
void mikeos_string_chomp(char *string);
int mikeos_string_compare(char *string1, char *string2);
void mikeos_string_copy(char *destination, char *source);
void mikeos_string_join(char *destination, char *source1, char *source2);
unsigned int mikeos_string_length(char *string);
void mikeos_string_lowercase(char *string);
void mikeos_string_parse(char *string, char **token1, char **token2, char**token3, char **token4);
void mikeos_string_reverse(char *string);
int mikeos_string_strincmp(char *string1, char *string2, unsigned int length);
void mikeos_string_strip(char *string, char character);
unsigned int mikeos_string_to_int(char *string);
char *mikeos_string_tokenize(char *string, char separator);
void mikeos_string_truncate(char *string, unsigned int length);
void mikeos_string_uppercase(char *string);
unsigned int mikeos_wait_for_key(void);
int mikeos_write_file(char *buf, char *filename, int size);
