void io_get_cpuid(unsigned long index, unsigned long *eax, unsigned long *ebx, unsigned long *ecx, unsigned long *edx);
unsigned short io_get_cs_register(void);
unsigned short io_get_ds_register(void);
void io_get_msr_register(unsigned long ecx, unsigned long *eax, unsigned long *edx);
void io_get_msr_register_amd(unsigned long ecx, unsigned long *eax, unsigned long *edx);
unsigned short io_get_ss_register(void);
void io_get_tsc_counter(unsigned long *low32, unsigned long *high32);
unsigned short io_input_port16(unsigned short port);
unsigned long io_input_port32(unsigned short port);
unsigned char io_input_port8(unsigned short port);
void io_output_port16(unsigned short port, unsigned short data);
void io_output_port32(unsigned short port, unsigned long data);
void io_output_port8(unsigned short port, unsigned char data);
unsigned short io_read_memory16(unsigned short *offset, unsigned short segment);
unsigned long io_read_memory32(unsigned long *offset, unsigned short segment);
unsigned char io_read_memory8(unsigned char *offset, unsigned short segment);
void io_set_msr_register(unsigned long index, unsigned long eax, unsigned long edx);
void io_set_msr_register_amd(unsigned long index, unsigned long eax, unsigned long edx);
void io_write_memory16(unsigned short *offset, unsigned short segment, unsigned short data);
void io_write_memory32(unsigned long *offset, unsigned short segment, unsigned long data);
void io_write_memory8(unsigned char *offset, unsigned short segment, unsigned char data);
